### ISSUE TITLE
Compiling on OSX

### ISSUE THREAD

**Issue by rvanvenetie** [NGSolve/ngsolve#11]
I can't get the current master to compile under OSx, see the error log: https://gist.github.com/rvanvenetie/873982a16d5fdb70497f36ea31c9b5bc.

I'm using clang 8.1.0 (clang-802.0.42).

**Comment by rvanvenetie** [comment]
Updated my apple clang to 9.0.0, and now the error seems to have disappeared.

**Comment by mhochsteger** [comment]
NGSolve is using C++-17 features. Thus, you need a recent compiler to build it, as you discovered correctly.
