### ISSUE TITLE
License clarity could be improved

### ISSUE THREAD

**Issue by kkremitzki** [NGSolve/ngsolve#13]
I can't find anywhere on ngsolve.org that shows the license; the only search result for "license" in the docs linked on ngsolve.org is https://ngsolve.org/docu/latest/i-tutorials/index.html?highlight=license which state:

> Copyright: The i-tutorials are a part of NGSolve and are covered by the LGPL open source license. You may extend and modify them for your use, but you have to refer to the original source.

There's also no LICENSE file in the repo which could be picked up automatically by Github. I also checked a few files for license headers but they aren't there either.

So, there are several ways the license clarity could be improved.

**Comment by mhochsteger** [comment]
Thanks for the report, I copied the license file to the root directory.
Best,
Matthias
