### ISSUE TITLE
ngscxx generated is invalid when netgen is already installed

### ISSUE THREAD

**Issue by Trophime** [NGSolve/ngsolve#25]
Hi,
I'm trying to package ngsolve on top of netgen fro Debian.
I ran into an issue with ngcxx, ngsld.

Would it be possible to change the main ngsolve CMakeLists.txt to 
account for an already installed netgen and not looking into NGSCXX_DIR
for netgen headers?

**Comment by ChrLackner** [comment]
Hi,
ngcxx and ngsld are scripts we install alongside with ngsolve to easier compile addon libraries. So NGSCXX_DIR should point to /usr/bin or something alike and add the paths for the netgen/ngsolve libraries to compiler/linker calls.
If you want to build ngsolve with an already installed netgen call cmake with
-DUSE_SUPERBUILD=OFF
this disables the superbuild that builds netgen+dependencies.

If this doesn't answer your question please feel free to reopen this issue.

Best
