### ISSUE TITLE
Building with HYPRE and MUMPS support

### ISSUE THREAD

**Issue by Trophime** [NGSolve/ngsolve#26]
When building with HYPRE and MUMS support there are tests that fail
whereas they don't fail without these options, namely:

* test_hidden.py
* test_periodic.py

Is this behavior normal?

Best

**Comment by ChrLackner** [comment]
Hi,
no, I build with HYPRE and MUMPS support and tests are running, can you specify more details? OS, cmake configuration versions of the linked libraries...
Actually I have no idea what these 2 test cases have to do with either of these libraries.
What do you mean by fail? Wrong results, segfaults, ... ?
