### ISSUE TITLE
Windows installer fails with 'media1.cab' corruption error

### ISSUE THREAD

**Issue by bzindovic** [NGSolve/ngsolve#35]
Install of v6.2.2105 on Windows 10 64-bit fails with the following message:
`The cabinet file 'media1.cab' required for this installation is corrupt and cannot be used.`
I've tried re-downloading and it is persistent error. Is this a packaging issue within the installer?

**Comment by torhans** [comment]
I get the same error!
Also tried to redownload the msi-file.

**Comment by russofel** [comment]
Hi! I have got the same problem...

**Comment by mhochsteger** [comment]
Do the nightly installers work for you?
https://www.asc.tuwien.ac.at/~mhochsteger/ngsolve/windows/?C=M;O=D

**Comment by torhans** [comment]
Yes, the installer works!

However I get the error

> AttributeError: module 'netgen.libngpy' has no attribute 'meshvis'

when doing
`from ngsolve import *`

**Comment by amy-metric** [comment]
I am also getting this same issue now. Was anyone able to sort this?

**Comment by bzindovic** [comment]
This issue seems to be resolved with the release of the new installer so will mark it as closed.
