### ISSUE TITLE
Cannot register for forum

### ISSUE THREAD

**Issue by blakseth** [NGSolve/ngsolve#44]
On Friday, I attempted to register for the forum on your webpage, but I received some error message implying that there was a problem sending the confirmation email. Unfortunately, I did not keep the entire error message because it specifically stated that the system had already notified the webpage owners of the error. When I later tried to log in with the account I created on Friday, I received an error message stating that the account had not been activated (or that it had been blocked, which I find less likely).

This week, I tried again to create an account with a different email-address and username. When trying to log into this new account using Firefox V97.0.1, I again get the error message stating that my account has been blocked or is not activated. In Chrome V98.0.4758.102, I do not get any error message, but login still fails. What happens on Chrome is simply that the login page refreshes, prompting me to re-enter all my details.

I have checked the inboxes (and spam filters) of both emails I have attempted to use for signing up to the forum, and I cannot find any activation emails related to NGSolve.

My apologies if this is not the appropriate place for this, but I did not know where else to contact you.

**Comment by mhochsteger** [comment]
Hello,

Thanks for the hint! We had to migrate the Forum to another server about a week ago, seems email/registration was not working since then. This is now fixed.
I also deleted the (non-activated) users you created, so please register again with the preferred username/email.
Reopen this issue if there are still troubles.

Best,
Matthias

**Comment by blakseth** [comment]
Thank you, Matthias. I want to bring to your attention that I received the following error message when using the url from the activation email: "Verification code not found. Check if your account is already activated and try to log in." In spite of this, the verification was successful, and I can now log in to my account. 

Best,
Sindre
