### ISSUE TITLE
SegFault from BilinearForm with Hesse Matrix

### ISSUE THREAD

**Issue by PaulSt** [NGSolve/ngsolve#51]
Hi :wave: 

I get a segfault when using SymbolicIntegrator with a Hesse Matrix in the following way
```
from ngsolve import *
from netgen.geom2d import unit_square
mesh = Mesh(unit_square.GenerateMesh(maxh=0.3))
fes = H1(mesh, order=4, dirichlet="")
u, v = fes.TnT()
Lap = lambda u : sum(Trace(u.Operator('hesse')))
a = BilinearForm(fes,symmetric=True)
a += InnerProduct(Lap(u)+u,v)*dx 
a.Assemble()
```
I narrowed it down to commit 3dee17ccefc9e0ea6294c62420a42d9e5292645c, which introduced the error for me.

However, simply splitting the terms works fine
```
a += InnerProduct(Lap(u),v)*dx + InnerProduct(u,v)*dx 
```

Cheers!

**Comment by mrambausek** [comment]
I'll have a look at it...

**Comment by mrambausek** [comment]
Thanks for reporting. Should be fixed in current master.
