### ISSUE TITLE
Mesh.Refine() does not update mesh.faces properly

### ISSUE THREAD

**Issue by Alex-Vasile** [NGSolve/ngsolve#52]
The issue I'm having is that the information provided by mesh.faces (edges, points, and facets may also have this issue) is not update correctly after a call to `mesh.Refine()`. Simple test case included below.

```Python
from ngsolve import Mesh
from netgen.geom2d import unit_square

mesh = Mesh(unit_square.GenerateMesh())

assert len(mesh.faces[0].edges) > 0

mesh.Refine()

empty_faces = []
for face in mesh.faces:
    if len(face.edges) == 0:
        empty_faces.append(face)
assert len(empty_faces) == 0  # This will fail
```

**Comment by sigmundholm** [comment]
The empty faces does seem very strange. After refinement, the mesh in your example has eight elements/faces, which make sense. However, the iterable `mesh.faces` has 10 elements, where two of these are empty. The numbering of the edges make sense with respect to the position of the elements, if you disregard the two empty elements/faces.

**Comment by Alex-Vasile** [comment]
> Hi, this is not a bug. Old facets are kept after refinement although they are no longer geometrically directly involved in the new mesh. But for setting up the grid hierarchy in Multigrid methods this is needed. Indeed you can simply disregard the facets without neighbors, they are simply kept from the coarser mesh.

Okay. That makes sense. I make my workarounds permanent then. (I refine then immediately save to file and load from file)
