### ISSUE TITLE
Struggling generating surface mesh in the .vtu format

### ISSUE THREAD

**Issue by isakhammer** [NGSolve/ngsolve#54]
I have lately tried to generate .vtu/.vtk files of mesh since I would like to work in ParaView as well. However, it is not possible to make an output of the 2d surface mesh by using the `perfstepsend=MeshingStep.MESHSURFACE` flag, while the 3d spherical mesh works fine. Any idea why?

 
Relevant documentation:

 -  [surface mesh generation](https://docu.ngsolve.org/nightly/i-tutorials/unit-6.1.1-surfacemeshes/surface_meshes.html?highlight=surface)
	
- [Vtk output](https://ngsolve.org/showcases/ngsolve/2-vtk-output)

Here is a minimal example

```
from ngsolve import *
from netgen.csg import *
from netgen.meshing import MeshingStep

def vtk_surface():
    geo = CSGeometry()
    geo.Add(Sphere(Pnt(0,0,0),1))
    
    # Generates sphere mesh (works!).
    mesh1 = Mesh(geo.GenerateMesh(maxh=0.5))
    vtk1 = VTKOutput(ma=mesh1,
                    filename="sphere",
                    subdivision=3)
    vtk1.Do()
    
    # Generates spherical shell surface mesh 
    # (does not work, shell.vtu file is almost empty and shows nothing in paraview).
    mesh2 = Mesh(geo.GenerateMesh(maxh=0.5, perfstepsend=MeshingStep.MESHSURFACE))
    vtk2 = VTKOutput(ma=mesh2,
                    filename="shell",
                    subdivision=3)
    vtk2.Do()

if __name__ == "__main__":
    vtk_surface()


```

**Comment by schruste** [comment]
Hi,

You have to specify that you want to export a surface also to the `VTKOutput`. There is the option `vb`, set it to `vb=BND` in the `Do`-Call and the surface mesh only will be exported. See also `help(VTKOutput)`.

Best,
schruste

**Comment by isakhammer** [comment]
Thanks for quick feedback!  :v:  The flag `vtk2.Do(vb=BND)` generated my surface mesh
