### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by Farahq11** [NGSolve/ngsolve#61]
I have trouble with downloading Netgen 6.2 on MacOS Catalina. I am not able to open Netgen to use it.

**Comment by Farahq11** [comment]
here is another screenshot I got. I downloaded 3.11 python but this required 3.8 I think. How do I find 3.8 for macOS?
![Screen Shot 2023-04-17 at 12 11 07 PM](https://user-images.githubusercontent.com/131007978/232559747-8a6ff29d-fb84-4453-aafa-cd59f070d793.png)

**Comment by mhochsteger** [comment]
I recommend using the pip package instead of the dmg bundle. Pip is also available for python 3.11.
See https://ngsolve.org/downloads for instructions.
