### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by mm-crj** [NGSolve/ngsolve#62]
In the documentation for [**Define and mesh 2D geometries**](https://github.com/NGSolve/ngsolve/blob/master/docs/netgen_tutorials/define_2d_geometries.rst) the first import should be
`import netgen.geom2d as geom2d` 
instead of 
`import netgen.geom2d as`

**Comment by mhochsteger** [comment]
Fixed in commit 0a257c98a6f2069b7bcda73641689152e723eca1, thanks!
