### ISSUE TITLE
Draw() display nothing

### ISSUE THREAD

**Issue by Thomas-GT40** [NGSolve/ngsolve#64]
Hi,
I'm Trying to do one of your tutorial, (3D solid Mechanics - https://docu.ngsolve.org/nightly/i-tutorials/wta/elasticity3D.html), 
but i don't succeed to display anything.
The code run ok, no errors, but it don't display anything.
I check jupyter, and it look like to be good.
Do you have any Idea what it can be ?
Thanks

**Comment by ChrLackner** [comment]
You run it with TCL gui? Then you need to remove the `from ngsolve.webgui import Draw` line probably.
